import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import SupervisorHeader from './SupervisorHeader';
import './AdminDashboard.css';

const baseURL = 'http://localhost:8000/api';

function SupervisorReports() {
    const navigate = useNavigate();
    const [interns, setInterns] = useState([]);
    const [selectedIntern, setSelectedIntern] = useState('');
    const [reportData, setReportData] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [searchQuery, setSearchQuery] = useState('');

    const token = localStorage.getItem('token');

    useEffect(() => {
        checkAccess();
        fetchInterns();
    }, []);

    const checkAccess = () => {
        const userRole = localStorage.getItem('userRole');
        if (userRole !== 'supervisor') {
            navigate('/login');
        }
    };

    const fetchInterns = async () => {
        try {
            const res = await axios.get(`${baseURL}/supervisor/interns/`, {
                headers: { Authorization: `Token ${token}` }
            });
            setInterns(res.data);
        } catch (err) {
            setError('Failed to fetch interns');
        }
    };

    const generateReport = async () => {
        if (!selectedIntern) {
            setError('Please select an intern');
            return;
        }

        try {
            setLoading(true);
            setError('');

            // Fetch intern details
            const internRes = await axios.get(`${baseURL}/supervisor/interns/${selectedIntern}/`, {
                headers: { Authorization: `Token ${token}` }
            });

            setReportData(internRes.data);
        } catch (err) {
            setError('Failed to generate report');
        } finally {
            setLoading(false);
        }
    };

    const downloadReport = () => {
        if (!reportData) return;

        const reportContent = `
INTERN PROGRESS REPORT
======================

Intern Information:
------------------
Name: ${reportData.name}
Student ID: ${reportData.student_id}
Email: ${reportData.email}
Course: ${reportData.course}
Position: ${reportData.position}

Tasks Summary:
-------------
Total Tasks: ${reportData.tasks?.length || 0}
${reportData.tasks?.map((task, i) => `
${i + 1}. ${task.title}
   Status: ${task.status}
   Priority: ${task.priority}
   Deadline: ${new Date(task.deadline).toLocaleDateString()}
   Description: ${task.description}
`).join('\n') || 'No tasks assigned'}

Attendance Summary:
------------------
Total Records: ${reportData.attendance?.length || 0}
${reportData.attendance?.slice(0, 10).map((att, i) => `
${i + 1}. Date: ${new Date(att.date).toLocaleDateString()}
   Status: ${att.status}
   Time In: ${att.time_in || 'N/A'}
   Time Out: ${att.time_out || 'N/A'}
`).join('\n') || 'No attendance records'}

Journal Entries:
---------------
Total Entries: ${reportData.journals?.length || 0}
${reportData.journals?.slice(0, 5).map((journal, i) => `
${i + 1}. Date: ${new Date(journal.date).toLocaleDateString()}
   Hours Worked: ${journal.hours_worked || 0}
   Description: ${journal.description || 'N/A'}
`).join('\n') || 'No journal entries'}

Report Generated: ${new Date().toLocaleString()}
Generated by: ${localStorage.getItem('username') || 'Supervisor'}
`;

        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${reportData.name.replace(/\s+/g, '_')}_Report_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
    };

    // Filter interns based on search query
    const filteredInterns = interns.filter(intern => {
        const searchLower = searchQuery.toLowerCase();
        return (
            intern.name?.toLowerCase().includes(searchLower) ||
            intern.student_id?.toLowerCase().includes(searchLower) ||
            intern.course?.toLowerCase().includes(searchLower)
        );
    });

    // Auto-select intern when search returns only one result
    useEffect(() => {
        if (filteredInterns.length === 1 && searchQuery) {
            setSelectedIntern(filteredInterns[0].id.toString());
        } else if (filteredInterns.length === 0 && searchQuery) {
            setSelectedIntern('');
        }
    }, [filteredInterns, searchQuery]);

    return (
        <div className="admin-dashboard-container">
            <div className="admin-dashboard-main">
                <SupervisorHeader
                    title="Reports & Downloads"
                    subtitle="Generate and download intern progress reports"
                />

                {error && <div className="alert alert-error">{error}</div>}

                {/* Report Generator */}
                <div style={{ background: 'white', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)', padding: '30px', marginBottom: '20px' }}>
                    <h2 style={{ margin: '0 0 20px 0' }}>Generate Intern Report</h2>

                    {/* Search Bar */}
                    <div style={{ marginBottom: '20px' }}>
                        <label style={{ display: 'block', marginBottom: '8px', fontWeight: '600' }}>
                            Search Intern
                        </label>
                        <div style={{ position: 'relative' }}>
                            <svg
                                width="20"
                                height="20"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="#718096"
                                strokeWidth="2"
                                style={{
                                    position: 'absolute',
                                    left: '12px',
                                    top: '50%',
                                    transform: 'translateY(-50%)',
                                    pointerEvents: 'none'
                                }}
                            >
                                <circle cx="11" cy="11" r="8" />
                                <path d="m21 21-4.35-4.35" />
                            </svg>
                            <input
                                type="text"
                                placeholder="Search by name, ID, or course..."
                                value={searchQuery}
                                onChange={(e) => setSearchQuery(e.target.value)}
                                style={{
                                    width: '100%',
                                    padding: '10px 10px 10px 40px',
                                    border: '1px solid #ddd',
                                    borderRadius: '4px',
                                    fontSize: '14px',
                                    outline: 'none',
                                    transition: 'border-color 0.3s ease'
                                }}
                                onFocus={(e) => e.target.style.borderColor = '#4CAF50'}
                                onBlur={(e) => e.target.style.borderColor = '#ddd'}
                            />
                        </div>
                        {searchQuery && (
                            <p style={{
                                margin: '8px 0 0 0',
                                fontSize: '0.85rem',
                                color: filteredInterns.length > 0 ? '#4CAF50' : '#f44336',
                                fontWeight: '500'
                            }}>
                                {filteredInterns.length === 0
                                    ? 'No interns found'
                                    : filteredInterns.length === 1
                                        ? '1 intern found - Auto-selected below'
                                        : `${filteredInterns.length} interns found`
                                }
                            </p>
                        )}
                    </div>

                    <div style={{ display: 'flex', gap: '15px', alignItems: 'flex-end', flexWrap: 'wrap' }}>
                        <div style={{ flex: '1', minWidth: '250px' }}>
                            <label style={{ display: 'block', marginBottom: '8px', fontWeight: '600' }}>
                                Select Intern
                            </label>
                            <select
                                value={selectedIntern}
                                onChange={(e) => setSelectedIntern(e.target.value)}
                                style={{
                                    width: '100%',
                                    padding: '10px',
                                    border: '1px solid #ddd',
                                    borderRadius: '4px',
                                    fontSize: '14px'
                                }}
                            >
                                <option value="">Choose an intern...</option>
                                {filteredInterns.length === 0 && searchQuery ? (
                                    <option disabled>No interns found matching your search</option>
                                ) : (
                                    filteredInterns.map(intern => (
                                        <option key={intern.id} value={intern.id}>
                                            {intern.name} ({intern.student_id})
                                        </option>
                                    ))
                                )}
                            </select>
                        </div>

                        <button
                            onClick={generateReport}
                            disabled={loading}
                            style={{
                                padding: '10px 30px',
                                background: loading ? '#ccc' : '#4CAF50',
                                color: 'white',
                                border: 'none',
                                borderRadius: '4px',
                                cursor: loading ? 'not-allowed' : 'pointer',
                                fontSize: '14px',
                                fontWeight: '600'
                            }}
                        >
                            {loading ? 'Generating...' : 'Generate Report'}
                        </button>
                    </div>
                </div>

                {/* Report Preview */}
                {reportData && (
                    <div style={{
                        background: 'white',
                        borderRadius: '16px',
                        boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
                        padding: '40px',
                        animation: 'fadeInUp 0.5s ease'
                    }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px' }}>
                            <h2 style={{
                                margin: 0,
                                fontSize: '1.8rem',
                                fontWeight: '700',
                                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                                WebkitBackgroundClip: 'text',
                                WebkitTextFillColor: 'transparent'
                            }}>
                                Report Preview
                            </h2>
                            <button
                                onClick={downloadReport}
                                style={{
                                    padding: '12px 24px',
                                    background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
                                    color: 'white',
                                    border: 'none',
                                    borderRadius: '10px',
                                    cursor: 'pointer',
                                    fontSize: '15px',
                                    fontWeight: '600',
                                    boxShadow: '0 4px 12px rgba(79, 172, 254, 0.4)',
                                    transition: 'all 0.3s ease',
                                    display: 'flex',
                                    alignItems: 'center',
                                    gap: '8px'
                                }}
                                onMouseEnter={(e) => {
                                    e.currentTarget.style.transform = 'translateY(-2px)';
                                    e.currentTarget.style.boxShadow = '0 6px 16px rgba(79, 172, 254, 0.5)';
                                }}
                                onMouseLeave={(e) => {
                                    e.currentTarget.style.transform = 'translateY(0)';
                                    e.currentTarget.style.boxShadow = '0 4px 12px rgba(79, 172, 254, 0.4)';
                                }}
                            >
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                                    <polyline points="7 10 12 15 17 10" />
                                    <line x1="12" y1="15" x2="12" y2="3" />
                                </svg>
                                Download Report
                            </button>
                        </div>

                        {/* Intern Info Card */}
                        <div style={{
                            marginBottom: '30px',
                            padding: '30px',
                            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                            borderRadius: '16px',
                            color: 'white',
                            boxShadow: '0 8px 24px rgba(102, 126, 234, 0.3)'
                        }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                                    <circle cx="12" cy="7" r="4" />
                                </svg>
                                <h3 style={{ margin: 0, fontSize: '1.4rem', fontWeight: '700' }}>Intern Information</h3>
                            </div>
                            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px' }}>
                                <div>
                                    <p style={{ margin: '0 0 4px 0', fontSize: '0.85rem', opacity: 0.9 }}>Full Name</p>
                                    <p style={{ margin: 0, fontSize: '1.1rem', fontWeight: '600' }}>{reportData.name}</p>
                                </div>
                                <div>
                                    <p style={{ margin: '0 0 4px 0', fontSize: '0.85rem', opacity: 0.9 }}>Student ID</p>
                                    <p style={{ margin: 0, fontSize: '1.1rem', fontWeight: '600' }}>{reportData.student_id}</p>
                                </div>
                                <div>
                                    <p style={{ margin: '0 0 4px 0', fontSize: '0.85rem', opacity: 0.9 }}>Email</p>
                                    <p style={{ margin: 0, fontSize: '1.1rem', fontWeight: '600' }}>{reportData.email}</p>
                                </div>
                                <div>
                                    <p style={{ margin: '0 0 4px 0', fontSize: '0.85rem', opacity: 0.9 }}>Course</p>
                                    <p style={{ margin: 0, fontSize: '1.1rem', fontWeight: '600' }}>{reportData.course}</p>
                                </div>
                                <div>
                                    <p style={{ margin: '0 0 4px 0', fontSize: '0.85rem', opacity: 0.9 }}>Position</p>
                                    <p style={{ margin: 0, fontSize: '1.1rem', fontWeight: '600' }}>{reportData.position}</p>
                                </div>
                            </div>
                        </div>

                        {/* Summary Stats */}
                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', marginBottom: '30px' }}>
                            <div style={{
                                padding: '24px',
                                background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
                                borderRadius: '12px',
                                color: 'white',
                                boxShadow: '0 4px 12px rgba(79, 172, 254, 0.3)'
                            }}>
                                <div style={{ fontSize: '0.85rem', opacity: 0.9, marginBottom: '8px' }}>Total Tasks</div>
                                <div style={{ fontSize: '2.5rem', fontWeight: '700' }}>{reportData.tasks?.length || 0}</div>
                            </div>
                            <div style={{
                                padding: '24px',
                                background: 'linear-gradient(135deg, #ff9f40 0%, #ff6b6b 100%)',
                                borderRadius: '12px',
                                color: 'white',
                                boxShadow: '0 4px 12px rgba(255, 159, 64, 0.3)'
                            }}>
                                <div style={{ fontSize: '0.85rem', opacity: 0.9, marginBottom: '8px' }}>Attendance Records</div>
                                <div style={{ fontSize: '2.5rem', fontWeight: '700' }}>{reportData.attendance?.length || 0}</div>
                            </div>
                            <div style={{
                                padding: '24px',
                                background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
                                borderRadius: '12px',
                                color: 'white',
                                boxShadow: '0 4px 12px rgba(240, 147, 251, 0.3)'
                            }}>
                                <div style={{ fontSize: '0.85rem', opacity: 0.9, marginBottom: '8px' }}>Journal Entries</div>
                                <div style={{ fontSize: '2.5rem', fontWeight: '700' }}>{reportData.journals?.length || 0}</div>
                            </div>
                        </div>

                        {/* Tasks Summary */}
                        <div style={{ marginBottom: '30px' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#4facfe" strokeWidth="2">
                                    <path d="M9 11l3 3L22 4" />
                                    <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
                                </svg>
                                <h3 style={{ margin: 0, fontSize: '1.3rem', fontWeight: '600', color: '#1a202c' }}>Tasks Summary</h3>
                            </div>
                            {reportData.tasks && reportData.tasks.length > 0 ? (
                                <div style={{ display: 'grid', gap: '12px' }}>
                                    {reportData.tasks.slice(0, 5).map((task, i) => (
                                        <div key={i} style={{
                                            padding: '20px',
                                            background: '#f7fafc',
                                            borderRadius: '12px',
                                            borderLeft: '4px solid #4facfe',
                                            transition: 'all 0.3s ease'
                                        }}
                                            onMouseEnter={(e) => {
                                                e.currentTarget.style.transform = 'translateX(4px)';
                                                e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.08)';
                                            }}
                                            onMouseLeave={(e) => {
                                                e.currentTarget.style.transform = 'translateX(0)';
                                                e.currentTarget.style.boxShadow = 'none';
                                            }}
                                        >
                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '8px' }}>
                                                <strong style={{ fontSize: '1.05rem', color: '#1a202c' }}>{task.title}</strong>
                                                <span style={{
                                                    padding: '4px 12px',
                                                    background: task.status === 'Completed' ? '#43e97b' : task.status === 'In Progress' ? '#4facfe' : '#ff9f40',
                                                    color: 'white',
                                                    borderRadius: '12px',
                                                    fontSize: '0.75rem',
                                                    fontWeight: '600'
                                                }}>
                                                    {task.status}
                                                </span>
                                            </div>
                                            <p style={{ margin: '8px 0', fontSize: '0.9rem', color: '#4a5568', lineHeight: '1.5' }}>{task.description}</p>
                                            <div style={{ display: 'flex', gap: '16px', fontSize: '0.85rem', color: '#718096' }}>
                                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
                                                        <line x1="16" y1="2" x2="16" y2="6" />
                                                        <line x1="8" y1="2" x2="8" y2="6" />
                                                        <line x1="3" y1="10" x2="21" y2="10" />
                                                    </svg>
                                                    Deadline: {new Date(task.deadline).toLocaleDateString()}
                                                </span>
                                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                                        <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
                                                    </svg>
                                                    Priority: {task.priority}
                                                </span>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <div style={{
                                    padding: '40px',
                                    textAlign: 'center',
                                    background: '#f7fafc',
                                    borderRadius: '12px',
                                    border: '2px dashed #e2e8f0'
                                }}>
                                    <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#cbd5e0" strokeWidth="2" style={{ margin: '0 auto 12px' }}>
                                        <path d="M9 11l3 3L22 4" />
                                        <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
                                    </svg>
                                    <p style={{ color: '#718096', fontStyle: 'italic', margin: 0 }}>No tasks assigned</p>
                                </div>
                            )}
                        </div>

                        {/* Attendance Summary */}
                        <div style={{ marginBottom: '30px' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ff9f40" strokeWidth="2">
                                    <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
                                    <line x1="16" y1="2" x2="16" y2="6" />
                                    <line x1="8" y1="2" x2="8" y2="6" />
                                    <line x1="3" y1="10" x2="21" y2="10" />
                                </svg>
                                <h3 style={{ margin: 0, fontSize: '1.3rem', fontWeight: '600', color: '#1a202c' }}>Attendance Summary</h3>
                            </div>
                            {reportData.attendance && reportData.attendance.length > 0 ? (
                                <div style={{
                                    background: '#f7fafc',
                                    borderRadius: '12px',
                                    overflow: 'hidden',
                                    border: '1px solid #e2e8f0'
                                }}>
                                    <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                                        <thead>
                                            <tr style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', color: 'white' }}>
                                                <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600' }}>Date</th>
                                                <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600' }}>Time In</th>
                                                <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600' }}>Time Out</th>
                                                <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600' }}>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {reportData.attendance.slice(0, 10).map((att, i) => (
                                                <tr key={i} style={{
                                                    borderBottom: '1px solid #e2e8f0',
                                                    background: i % 2 === 0 ? 'white' : '#f7fafc'
                                                }}>
                                                    <td style={{ padding: '14px', fontWeight: '500' }}>{new Date(att.date).toLocaleDateString()}</td>
                                                    <td style={{ padding: '14px', color: '#4a5568' }}>{att.time_in || '-'}</td>
                                                    <td style={{ padding: '14px', color: '#4a5568' }}>{att.time_out || '-'}</td>
                                                    <td style={{ padding: '14px' }}>
                                                        <span style={{
                                                            padding: '4px 12px',
                                                            background: att.status === 'Present' ? '#43e97b' : '#ff9f40',
                                                            color: 'white',
                                                            borderRadius: '12px',
                                                            fontSize: '0.75rem',
                                                            fontWeight: '600'
                                                        }}>
                                                            {att.status}
                                                        </span>
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            ) : (
                                <div style={{
                                    padding: '40px',
                                    textAlign: 'center',
                                    background: '#f7fafc',
                                    borderRadius: '12px',
                                    border: '2px dashed #e2e8f0'
                                }}>
                                    <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#cbd5e0" strokeWidth="2" style={{ margin: '0 auto 12px' }}>
                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
                                        <line x1="16" y1="2" x2="16" y2="6" />
                                        <line x1="8" y1="2" x2="8" y2="6" />
                                        <line x1="3" y1="10" x2="21" y2="10" />
                                    </svg>
                                    <p style={{ color: '#718096', fontStyle: 'italic', margin: 0 }}>No attendance records</p>
                                </div>
                            )}
                        </div>

                        {/* Journal Summary */}
                        <div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#f5576c" strokeWidth="2">
                                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                                    <polyline points="14 2 14 8 20 8" />
                                    <line x1="16" y1="13" x2="8" y2="13" />
                                    <line x1="16" y1="17" x2="8" y2="17" />
                                    <polyline points="10 9 9 9 8 9" />
                                </svg>
                                <h3 style={{ margin: 0, fontSize: '1.3rem', fontWeight: '600', color: '#1a202c' }}>Journal Entries</h3>
                            </div>
                            {reportData.journals && reportData.journals.length > 0 ? (
                                <div style={{ display: 'grid', gap: '12px' }}>
                                    {reportData.journals.slice(0, 5).map((journal, i) => (
                                        <div key={i} style={{
                                            padding: '20px',
                                            background: '#f7fafc',
                                            borderRadius: '12px',
                                            borderLeft: '4px solid #f5576c',
                                            transition: 'all 0.3s ease'
                                        }}
                                            onMouseEnter={(e) => {
                                                e.currentTarget.style.transform = 'translateX(4px)';
                                                e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.08)';
                                            }}
                                            onMouseLeave={(e) => {
                                                e.currentTarget.style.transform = 'translateX(0)';
                                                e.currentTarget.style.boxShadow = 'none';
                                            }}
                                        >
                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                                                <strong style={{ fontSize: '1.05rem', color: '#1a202c' }}>
                                                    {new Date(journal.date).toLocaleDateString('en-US', {
                                                        weekday: 'long',
                                                        year: 'numeric',
                                                        month: 'long',
                                                        day: 'numeric'
                                                    })}
                                                </strong>
                                                <span style={{
                                                    padding: '4px 12px',
                                                    background: '#f5576c',
                                                    color: 'white',
                                                    borderRadius: '12px',
                                                    fontSize: '0.75rem',
                                                    fontWeight: '600'
                                                }}>
                                                    {journal.hours_worked || 0} hours
                                                </span>
                                            </div>
                                            <p style={{ margin: 0, fontSize: '0.9rem', color: '#4a5568', lineHeight: '1.6' }}>
                                                {journal.description || 'No description provided'}
                                            </p>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <div style={{
                                    padding: '40px',
                                    textAlign: 'center',
                                    background: '#f7fafc',
                                    borderRadius: '12px',
                                    border: '2px dashed #e2e8f0'
                                }}>
                                    <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#cbd5e0" strokeWidth="2" style={{ margin: '0 auto 12px' }}>
                                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                                        <polyline points="14 2 14 8 20 8" />
                                    </svg>
                                    <p style={{ color: '#718096', fontStyle: 'italic', margin: 0 }}>No journal entries</p>
                                </div>
                            )}
                        </div>

                        {/* Report Footer */}
                        <div style={{
                            marginTop: '40px',
                            padding: '20px',
                            background: 'linear-gradient(135deg, #f7fafc 0%, #e2e8f0 100%)',
                            borderRadius: '12px',
                            textAlign: 'center',
                            border: '1px solid #e2e8f0'
                        }}>
                            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '24px', flexWrap: 'wrap' }}>
                                <span style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.9rem', color: '#4a5568', fontWeight: '500' }}>
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                                        <polyline points="14 2 14 8 20 8" />
                                        <line x1="16" y1="13" x2="8" y2="13" />
                                        <line x1="16" y1="17" x2="8" y2="17" />
                                    </svg>
                                    Report Generated: {new Date().toLocaleString()}
                                </span>
                                <span style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.9rem', color: '#4a5568', fontWeight: '500' }}>
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                                        <circle cx="12" cy="7" r="4" />
                                    </svg>
                                    Generated by: {localStorage.getItem('username') || 'Supervisor'}
                                </span>
                            </div>
                        </div>
                    </div>
                )}

                <style>{`
                    @keyframes fadeInUp {
                        from {
                            opacity: 0;
                            transform: translateY(30px);
                        }
                        to {
                            opacity: 1;
                            transform: translateY(0);
                        }
                    }
                `}</style>
            </div>
        </div>
    );
}

export default SupervisorReports;
