# Generated by Django 4.2.16 on 2025-11-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_feedback_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
