# Generated by Django 4.2.16 on 2025-11-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_internship_position_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='position_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], default='Full-time', max_length=50),
        ),
    ]
