# Generated by Django 4.2.16 on 2025-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_supportticket_supervisor_pretrainingrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, help_text="Student's course/program", max_length=200),
        ),
    ]
