# Generated by Django 4.2.16 on 2025-11-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studentprofile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
    ]
