# Generated by Django 4.2.16 on 2025-11-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_studentprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
