# Generated by Django 4.2.16 on 2025-11-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='certificate_of_registration',
            field=models.FileField(blank=True, help_text='Certificate of Registration (COR) document', null=True, upload_to='certificates_of_registration/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cor_verified',
            field=models.BooleanField(default=False, help_text='Whether the COR has been verified by the student'),
        ),
    ]
