# Generated by Django 4.2.26 on 2025-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_studentprofile_certificate_of_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='required_courses',
            field=models.TextField(blank=True, help_text='Comma-separated required/preferred courses (e.g., BSCS, BS INFO TECH)'),
        ),
    ]
