# Generated by Django 5.2.7 on 2025-12-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_name',
            field=models.CharField(default='EARIST Internship System', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='system_email',
            field=models.EmailField(default='earistojtsys@gmail.com', max_length=254),
        ),
    ]
