# Generated by Django 5.2.7 on 2025-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_studentprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='certification_file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
