# Generated by Django 5.2.7 on 2025-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Student's date of birth", null=True),
        ),
    ]
