# Generated by Django 5.2.9 on 2025-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_studentprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
