# Generated by Django 5.2.9 on 2025-12-03 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, choices=[('CAS', 'College of Arts and Sciences'), ('CBA', 'College of Business Administration'), ('CED', 'College of Education'), ('CEN', 'College of Engineering'), ('CHM', 'College of Hospitality Management'), ('CIT', 'College of Industrial Technology'), ('CPAC', 'College of Public Administration and Criminology'), ('CAFA', 'College of Architecture and Fine Arts'), ('GS', 'Graduate School')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CBA', 'College of Business Administration'), ('CED', 'College of Education'), ('CEN', 'College of Engineering'), ('CHM', 'College of Hospitality Management'), ('CIT', 'College of Industrial Technology'), ('CPAC', 'College of Public Administration and Criminology'), ('CAFA', 'College of Architecture and Fine Arts'), ('GS', 'Graduate School')], max_length=10)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
