# Generated by Django 5.2.9 on 2025-12-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_studentprofile_college_coordinatorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='college',
            field=models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CBA', 'College of Business Administration'), ('CED', 'College of Education'), ('CEN', 'College of Engineering'), ('CHM', 'College of Hospitality Management'), ('CIT', 'College of Industrial Technology'), ('CPAC', 'College of Public Administration and Criminology'), ('CAFA', 'College of Architecture and Fine Arts'), ('CCS', 'College of Computer Studies'), ('GS', 'Graduate School')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, choices=[('CAS', 'College of Arts and Sciences'), ('CBA', 'College of Business Administration'), ('CED', 'College of Education'), ('CEN', 'College of Engineering'), ('CHM', 'College of Hospitality Management'), ('CIT', 'College of Industrial Technology'), ('CPAC', 'College of Public Administration and Criminology'), ('CAFA', 'College of Architecture and Fine Arts'), ('CCS', 'College of Computer Studies'), ('GS', 'Graduate School')], max_length=10, null=True),
        ),
    ]
