# Generated by Django 5.2.9 on 2025-12-04 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_company_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Percentage weight (0-100)', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supervisor_rating_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('requirements_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=50)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
