# Generated by Django 5.2.9 on 2025-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_narrativereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='target_colleges',
            field=models.JSONField(blank=True, default=list, help_text='Colleges this company is targeting for recruitment'),
        ),
    ]
