# Generated by Django 5.2.9 on 2025-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_company_target_colleges'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='moa_expiration_date',
            field=models.DateField(blank=True, help_text='Expiration date of the MOA', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='moa_file',
            field=models.FileField(blank=True, help_text='Memorandum of Agreement document', null=True, upload_to='moa_documents/'),
        ),
        migrations.AddField(
            model_name='company',
            name='moa_start_date',
            field=models.DateField(blank=True, help_text='Start date of the MOA', null=True),
        ),
    ]
