# Generated by Django 5.2.9 on 2025-12-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_company_moa_expiration_date_company_moa_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='department',
            field=models.CharField(blank=True, help_text='Target college (e.g., CCS, CEN)', max_length=10),
        ),
    ]
