# Generated by Django 5.2.9 on 2025-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_companyuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='department',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='target_colleges',
            field=models.JSONField(blank=True, default=list, help_text='Colleges this supervisor is targeting'),
        ),
    ]
