# Generated by Django 5.2.9 on 2025-12-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='duration_weeks',
        ),
        migrations.AddField(
            model_name='internship',
            name='duration_hours',
            field=models.PositiveIntegerField(default=300, help_text='Total hours required'),
        ),
    ]
