# Generated by Django 5.2.9 on 2025-12-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_internship_duration_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date when internship was completed', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
