# Generated by Django 5.2.7 on 2025-12-16 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_application_completed_at_alter_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Backup recovery code', max_length=10, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this code has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this code was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='User-friendly device name (e.g., Chrome on Windows)', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this trust expires')),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('2FA_VERIFIED', '2FA Verified Successfully'), ('2FA_FAILED', '2FA Verification Failed'), ('BACKUP_CODE_USED', 'Backup Code Used'), ('BACKUP_CODES_GENERATED', 'Backup Codes Generated'), ('DEVICE_TRUSTED', 'Device Marked as Trusted'), ('DEVICE_UNTRUSTED', 'Device Removed from Trusted')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2FA Audit Log',
                'verbose_name_plural': '2FA Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='TOTP secret key', max_length=32)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has verified their 2FA setup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_at', models.DateTimeField(blank=True, help_text='When 2FA was enabled', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time 2FA was used', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentications',
            },
        ),
    ]
