# Generated by Django 5.2.7 on 2025-12-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='preferred_method',
            field=models.CharField(choices=[('app', 'Authenticator App (Google Authenticator, Authy, etc.)'), ('email', 'Email OTP')], default='email', help_text="User's preferred 2FA method", max_length=10),
        ),
    ]
