# Generated by Django 5.2.7 on 2025-12-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_twofactorauth_preferred_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach images or documents (jpg, png, pdf, docx)', null=True, upload_to='message_attachments/'),
        ),
    ]
