# Generated by Django 5.2.7 on 2025-12-17 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_update_evaluation_scale_and_grades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Approval', 'Approval Document'), ('Certificate', 'Certificate'), ('Completion', 'Completion Form'), ('Evaluation', 'Evaluation Form'), ('Recommendation', 'Recommendation Letter'), ('Other', 'Other Document')], default='Other', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='supervisor_documents/')),
                ('is_official', models.BooleanField(default=True, help_text='Official document with signature/seal')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_documents', to='core.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_supervisor_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Document',
                'verbose_name_plural': 'Supervisor Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
