# Generated by Django 5.2.7 on 2025-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('Evaluation Form', 'Evaluation Form'), ('Waiver', 'Waiver'), ('Consent Letter', 'Consent Letter'), ('Training Plan', 'Training Plan'), ('Contract', 'Contract'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pretrainingrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('Recommendation Letter', 'Recommendation Letter'), ('Waiver', 'Waiver'), ('Consent Letter', 'Consent Letter'), ('Contract', 'Contract'), ('Medical Certificate', 'Medical Certificate'), ('Other', 'Other')], max_length=50),
        ),
    ]
