# Generated by Django 5.2.7 on 2025-12-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_documenttemplate_template_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='college',
            field=models.CharField(blank=True, help_text='College this template is for (leave blank for all colleges)', max_length=10, null=True),
        ),
    ]
