# Generated by Django 5.2.7 on 2025-12-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_message_delivered_at_message_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
