# Generated by Django 5.2.7 on 2026-01-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_message_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorprofile',
            name='office_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
