# Generated by Django 5.2.7 on 2026-01-14 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_coordinatorprofile_office_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Endorsement Letter')", max_length=200)),
                ('code', models.CharField(help_text="Internal code (e.g., 'endorsement_letter')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this document is for')),
                ('category', models.CharField(choices=[('Letters', 'Letters'), ('Certificates', 'Certificates'), ('Legal Documents', 'Legal Documents'), ('Reports', 'Reports')], default='Letters', max_length=50)),
                ('requires_student', models.BooleanField(default=False, help_text='Does this document require student selection?')),
                ('requires_company', models.BooleanField(default=False, help_text='Does this document require company selection?')),
                ('is_enabled', models.BooleanField(default=True, help_text='Is this document type available for generation?')),
                ('college', models.CharField(blank=True, choices=[('CAS', 'College of Arts and Sciences'), ('CBA', 'College of Business Administration'), ('CED', 'College of Education'), ('CEN', 'College of Engineering'), ('CHM', 'College of Hospitality Management'), ('CIT', 'College of Industrial Technology'), ('CPAC', 'College of Public Administration and Criminology'), ('CAFA', 'College of Architecture and Fine Arts'), ('CCS', 'College of Computer Studies'), ('GS', 'Graduate School')], help_text='College this document type is for (leave blank for all colleges)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Type Configuration',
                'verbose_name_plural': 'Document Type Configurations',
                'ordering': ['category', 'name'],
            },
        ),
    ]
