# Generated by Django 5.2.7 on 2026-01-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_documenttypeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypeconfig',
            name='template_file',
            field=models.FileField(blank=True, help_text='Custom template file (DOCX) for this document type', null=True, upload_to='document_type_templates/'),
        ),
    ]
