# Generated by Django 5.2.7 on 2026-01-14 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_documenttypeconfig_template_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_config', models.JSONField(blank=True, default=list)),
                ('required_docs', models.JSONField(blank=True, default=list)),
                ('cutoff_dates', models.JSONField(blank=True, default=list)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coordinator Settings',
            },
        ),
    ]
