# Generated by Django 5.2.7 on 2026-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_coordinatorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Date when this notice expires', null=True),
        ),
    ]
