# Generated by Django 5.2.7 on 2026-01-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_notice_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretrainingrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('Resume/CV', 'Resume/CV'), ('Application Letter', 'Application Letter'), ('Endorsement Letter', 'Endorsement Letter'), ('Recommendation Letter', 'Recommendation Letter'), ('Waiver', 'Waiver'), ('Consent Letter', 'Consent Letter'), ('Contract', 'Contract'), ('Medical Certificate', 'Medical Certificate'), ('NBI Clearance', 'NBI Clearance'), ('Barangay Clearance', 'Barangay Clearance'), ('Other', 'Other')], max_length=50),
        ),
    ]
