# Generated by Django 5.2.7 on 2026-01-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_pretrainingrequirement_requirement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypeconfig',
            name='template_file_pdf',
            field=models.FileField(blank=True, help_text='Custom template file (PDF) for this document type - used for PDF output consistency', null=True, upload_to='document_type_templates/'),
        ),
    ]
