# Generated by Django 5.2.7 on 2026-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_documenttypeconfig_template_file_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='problem_solving',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='punctuality',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='teamwork',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='work_quality',
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='criteria_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Structured scores for Areas 1-4'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments / Suggestions'),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade Equivalent (e.g. 1.0, 1.25)', max_length=10),
        ),
    ]
