# Generated by Django 5.2.7 on 2026-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_performanceevaluation_areas_for_improvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submissions/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
    ]
