# Generated by Django 5.2.7 on 2026-01-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_task_submission_file_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_link',
            field=models.URLField(blank=True, help_text='External link (e.g., Google Drive, GitHub)', null=True),
        ),
    ]
