# Generated by Django 5.2.7 on 2026-01-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_task_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Total hours required', null=True),
        ),
    ]
