# Generated by Django 5.2.7 on 2026-01-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_internship_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='terminated_at',
            field=models.DateTimeField(blank=True, help_text='Date when internship was terminated', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='termination_reason',
            field=models.TextField(blank=True, help_text='Reason for termination by supervisor'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], default='Pending', max_length=50),
        ),
    ]
