# Generated by Django 5.2.7 on 2026-01-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_application_terminated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('Endorsement Letter', 'Endorsement Letter'), ('Acceptance Letter', 'Acceptance Letter'), ('Evaluation Form', 'Evaluation Form'), ('Waiver', 'Waiver'), ('Consent Letter', 'Consent Letter'), ('Training Plan', 'Training Plan'), ('Contract', 'Contract'), ('Medical Certificate', 'Medical Certificate'), ('Other', 'Other')], max_length=50),
        ),
    ]
