# Generated by Django 5.2.7 on 2026-01-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_documenttemplate_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parents_consent',
            field=models.FileField(blank=True, help_text="Parent's consent letter (PDF, Doc, Image)", null=True, upload_to='application_consents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='student_health_record',
            field=models.FileField(blank=True, help_text='Student health record (PDF, Doc, Image)', null=True, upload_to='application_health_records/'),
        ),
    ]
