# Generated by Django 5.2.7 on 2026-01-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_application_parents_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='internship_contract',
            field=models.FileField(blank=True, help_text='Internship Contract (PDF, Doc, Image)', null=True, upload_to='application_contracts/'),
        ),
    ]
