# Generated by Django 5.2.7 on 2026-01-19 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_application_internship_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='supervisor_email',
            field=models.EmailField(blank=True, help_text='Email of company supervisor who evaluated', max_length=254),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text='Name of company supervisor who evaluated', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='qr_code_image',
            field=models.TextField(blank=True, help_text='Base64-encoded QR code image', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='qr_code_token',
            field=models.CharField(blank=True, help_text='Permanent encrypted token for QR code', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_evaluations', to=settings.AUTH_USER_MODEL),
        ),
    ]
