# Generated by Django 5.2.7 on 2026-01-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_performanceevaluation_supervisor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='supervisor_position',
            field=models.CharField(blank=True, help_text='Position/Title of supervisor', max_length=255),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='supervisor_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image'),
        ),
    ]
